<?xml version="1.0" encoding="UTF-8"?>
<!-- 内部DTD 亦可通过外部DTD来实现-->
<!DOCTYPE generatorConfiguration

        [
                <!ELEMENT generatorConfiguration (properties?, classPathEntry*, context+)>

                <!ELEMENT properties EMPTY>
                <!ATTLIST properties
                        resource CDATA #IMPLIED
                        url CDATA #IMPLIED>
                <!--
                           括号里是声明出现的次序:
                    *: 出现任意次,包括0次
                    ?: 出现最多一次
                    |:选择之一
                    +: 出现最少1次
                    如果没有上述符号:必须且只能出现一次
                 -->
                <!ELEMENT context (property*, plugin*, commentGenerator?, (connectionFactory | jdbcConnection), javaTypeResolver?,
                        javaModelGenerator, sqlMapGenerator, javaClientGenerator, javaServiceGenerator,table+)>
                <!ATTLIST context id ID #REQUIRED
                        defaultModelType CDATA #IMPLIED
                        targetRuntime CDATA #IMPLIED
                        introspectedColumnImpl CDATA #IMPLIED>

                <!ELEMENT connectionFactory (property*)>
                <!ATTLIST connectionFactory
                        type CDATA #IMPLIED>

                <!ELEMENT jdbcConnection (property*)>
                <!ATTLIST jdbcConnection
                        driverClass CDATA #REQUIRED
                        connectionURL CDATA #REQUIRED
                        userId CDATA #IMPLIED
                        password CDATA #IMPLIED>

                <!ELEMENT classPathEntry EMPTY>
                <!ATTLIST classPathEntry
                        location CDATA #REQUIRED>

                <!ELEMENT property EMPTY>
                <!ATTLIST property
                        name CDATA #REQUIRED
                        value CDATA #REQUIRED>

                <!ELEMENT plugin (property*)>
                <!ATTLIST plugin
                        type CDATA #REQUIRED>

                <!ELEMENT javaModelGenerator (property*)>
                <!ATTLIST javaModelGenerator
                        targetPackage CDATA #REQUIRED
                        targetProject CDATA #REQUIRED>

                <!ELEMENT javaTypeResolver (property*)>
                <!ATTLIST javaTypeResolver
                        type CDATA #IMPLIED>

                <!ELEMENT sqlMapGenerator (property*)>
                <!ATTLIST sqlMapGenerator
                        targetPackage CDATA #REQUIRED
                        targetProject CDATA #REQUIRED>

                <!ELEMENT javaClientGenerator (property*)>
                <!ATTLIST javaClientGenerator
                        type CDATA #REQUIRED
                        targetPackage CDATA #REQUIRED
                        targetProject CDATA #REQUIRED
                        implementationPackage CDATA #IMPLIED>
                <!--javaServiceGenerator -->
                <!ELEMENT javaServiceGenerator (property*)>
                <!ATTLIST javaServiceGenerator
                        targetPackage CDATA #REQUIRED
                        implementationPackage CDATA #REQUIRED
                        targetProject CDATA #REQUIRED>

                <!ELEMENT table (property*, generatedKey?, domainObjectRenamingRule?, columnRenamingRule?, (columnOverride | ignoreColumn | ignoreColumnsByRegex)*) >
                <!ATTLIST table
                        catalog CDATA #IMPLIED
                        schema CDATA #IMPLIED
                        tableName CDATA #REQUIRED
                        alias CDATA #IMPLIED
                        domainObjectName CDATA #IMPLIED
                        mapperName CDATA #IMPLIED
                        sqlProviderName CDATA #IMPLIED
                        enableInsert CDATA #IMPLIED
                        enableSelectByPrimaryKey CDATA #IMPLIED
                        enableSelectByExample CDATA #IMPLIED
                        enableUpdateByPrimaryKey CDATA #IMPLIED
                        enableDeleteByPrimaryKey CDATA #IMPLIED
                        enableDeleteByExample CDATA #IMPLIED
                        enableCountByExample CDATA #IMPLIED
                        enableUpdateByExample CDATA #IMPLIED
                        selectByPrimaryKeyQueryId CDATA #IMPLIED
                        selectByExampleQueryId CDATA #IMPLIED
                        modelType CDATA #IMPLIED
                        escapeWildcards CDATA #IMPLIED
                        delimitIdentifiers CDATA #IMPLIED
                        delimitAllColumns CDATA #IMPLIED>

                <!ELEMENT columnOverride (property*)>
                <!ATTLIST columnOverride
                        column CDATA #REQUIRED
                        property CDATA #IMPLIED
                        javaType CDATA #IMPLIED
                        jdbcType CDATA #IMPLIED
                        typeHandler CDATA #IMPLIED
                        isGeneratedAlways CDATA #IMPLIED
                        delimitedColumnName CDATA #IMPLIED>

                <!ELEMENT ignoreColumn EMPTY>
                <!ATTLIST ignoreColumn
                        column CDATA #REQUIRED
                        delimitedColumnName CDATA #IMPLIED>


                <!ELEMENT ignoreColumnsByRegex (except*)>
                <!ATTLIST ignoreColumnsByRegex
                        pattern CDATA #REQUIRED>

                <!ELEMENT except EMPTY>
                <!ATTLIST except
                        column CDATA #REQUIRED
                        delimitedColumnName CDATA #IMPLIED>

                <!ELEMENT generatedKey EMPTY>
                <!ATTLIST generatedKey
                        column CDATA #REQUIRED
                        sqlStatement CDATA #REQUIRED
                        identity CDATA #IMPLIED
                        type CDATA #IMPLIED>

                <!ELEMENT domainObjectRenamingRule EMPTY>
                <!ATTLIST domainObjectRenamingRule
                        searchString CDATA #REQUIRED
                        replaceString CDATA #IMPLIED>

                <!ELEMENT columnRenamingRule EMPTY>
                <!ATTLIST columnRenamingRule
                        searchString CDATA #REQUIRED
                        replaceString CDATA #IMPLIED>

                <!ELEMENT commentGenerator (property*)>
                <!ATTLIST commentGenerator
                        type CDATA #IMPLIED>
                ]
        >

<generatorConfiguration>
    <context id="ables" targetRuntime="MyBatis3">

        <plugin type="run.override.PluginChain" />
        <plugin type="run.override.SerializablePlugin" />
        <plugin type="org.mybatis.generator.plugins.ToStringPlugin" />
        <commentGenerator type="run.override.CommentGenerator"/>

        <jdbcConnection driverClass="com.mysql.jdbc.Driver"
                        connectionURL="jdbc:mysql://10.67.12.233:3306/elecsign?characterEncoding=utf8"
                        userId="dianqian" password="abcd1234">
        </jdbcConnection>
        <javaTypeResolver>
            <property name="forceBigDecimals" value="false" />
        </javaTypeResolver>
        <javaModelGenerator targetPackage="cn.creditease.elecsign.model" targetProject=".\src">
            <property name="enableSubPackages" value="false" />
            <property name="trimStrings" value="true" />
        </javaModelGenerator>

        <sqlMapGenerator targetPackage="mapper.cn.creditease.elecsign.dao" targetProject=".\src">
            <property name="enableSubPackages" value="false" />
        </sqlMapGenerator>

        <javaClientGenerator type="XMLMAPPER" targetPackage="cn.creditease.elecsign.dao" targetProject=".\src">
            <property name="enableSubPackages" value="false" />
        </javaClientGenerator>
        <javaServiceGenerator  targetPackage="cn.creditease.elecsign.service.business"
                               implementationPackage = "cn.creditease.elecsign.service.business.impl" targetProject=".\src">
            <property name="enableSubPackages" value="false" />
        </javaServiceGenerator>


        <!-- 批次表，针对批量的异步操作 -->
        <!--<table tableName="els_asynchronous" domainObjectName="ElsAsynchronous"
            alias="elsAsynchronous">
            <generatedKey column="id" sqlStatement="MySql" identity="true" />
        </table>-->

        <!-- 批量明细表，针对批量的异步操作 -->
        <!--<table tableName="els_account" domainObjectName="els_account"
               alias="els_account">
            <generatedKey column="id" sqlStatement="MySql" identity="true" />
        </table>-->
        <!-- 批量明细表，针对批量的异步操作 -->
        <!--<table tableName="els_asynchronous_detail" domainObjectName="ElsAsynchronousDetail"
               alias="els_account">
            <generatedKey column="id" sqlStatement="MySql" identity="true" />
        </table>-->
        <!-- 商户配置信息表 -->
        <!--<table tableName="els_merchant_cfg" domainObjectName="ElsMerchantCfg"-->
               <!--alias="elsMerchantCfg">-->
            <!--<generatedKey column="id" sqlStatement="MySql" identity="true" />-->
        <!--</table>-->

        <!-- 账户信息表 -->
        <!--<table tableName="els_account" domainObjectName="ElsAccount"
               alias="elsAccount">
            <generatedKey column="id" sqlStatement="MySql" identity="true" />
        </table>-->

        <!-- 数字证书信息表 -->
        <!--<table tableName="els_cert" domainObjectName="ElsCert"
               alias="elsCert">
            <generatedKey column="id" sqlStatement="MySql" identity="true" />
        </table>-->

        <!--存证第三方接口调用记录-->
        <!--<table tableName="els_notarystorage_interface_call" domainObjectName="ElsNotarystorageInterfaceCall"
               alias="elsNotarystorageInterfaceCall">
            <generatedKey column="id" sqlStatement="MySql" identity="true" />
        </table>-->

        <!--<table tableName="els_verifyid_interface_call" domainObjectName="ElsVerifyidInterfaceCall"
               alias="elsVerifyidInterfaceCall">
            <generatedKey column="id" sqlStatement="MySql" identity="true" />
        </table>-->

        <!--<table tableName="els_real_name_auth_record" domainObjectName="ElsRealNameAuthRecord"-->
               <!--alias="elsRealNameAuthRecord">-->
            <!--<generatedKey column="id" sqlStatement="MySql" identity="true" />-->
        <!--</table>-->

        <!--<table tableName="els_doc_record" domainObjectName="ElsDocRecord"
               alias="elsDocRecord">
            <generatedKey column="id" sqlStatement="MySql" identity="true" />
        </table>-->
        <!--商户信息-->
        <!--<table tableName="els_merchant" domainObjectName="ElsMerchant"
               alias="elsMerchant">
            <generatedKey column="id" sqlStatement="MySql" identity="true" />
        </table>-->

        <!--请求链接令牌信息-->
        <table tableName="els_hpage_token" domainObjectName="ElsHpageToken"
               alias="elsHpageToken">
            <generatedKey column="id" sqlStatement="MySql" identity="true" />
        </table>

        <!--文件组信息-->
        <!--<table tableName="els_bundle" domainObjectName="ElsBundle"
               alias="elsBundle">
            <generatedKey column="id" sqlStatement="MySql" identity="true" />
        </table>-->

    </context>
</generatorConfiguration>
